### ISSUE TITLE
Invalid argument(s): No such library: dart.convert

### ISSUE THREAD

**Issue by RicoLiu** [google/reflectable.dart#272]
Hi

When I invoked the `findLibrary` method, it got error likes:

```shell
Unhandled exception:
Invalid argument(s): No such library: dart.convert
#0      ReflectableImpl.findLibrary (package:reflectable/src/reflectable_builder_based.dart:2596:9)
#1      main (package:ast2dsl/main_entry/main.dart:102:36)
#2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

Code:
```
class Reflectable extends Reflectable {
  const Reflectable()
      : super(
          instanceInvokeCapability,
          libraryCapability,
          staticInvokeCapability,
          topLevelInvokeCapability,
          newInstanceCapability,
          metadataCapability,
          reflectedTypeCapability,
          declarationsCapability,
          invokingCapability,
        );
}

const reflect = Reflectable();

 var libraryMirror = gfyReflect.findLibrary('dart.convert');
 var global_res = libraryMirror.invoke('jsonDecode', ['{"name": "test123"}']);
```

something goes wrong?

**Comment by RicoLiu** [comment]
change 
```
class Reflectable extends Reflectable {
  const Reflectable()
      : super(
          instanceInvokeCapability,
          libraryCapability,
          staticInvokeCapability,
          topLevelInvokeCapability,
          newInstanceCapability,
          metadataCapability,
          reflectedTypeCapability,
          declarationsCapability,
          invokingCapability,
        );
}
```

to

```
class Reflectable extends Reflectable {
const GfyReflectable()
      : super(
          instanceInvokeCapability,
          libraryCapability,
          staticInvokeCapability,
          const TopLevelInvokeCapability(r'^(jsonDecode)$'),
          newInstanceCapability,
          metadataCapability,
          reflectedTypeCapability,
          declarationsCapability,
          invokingCapability,
          superclassQuantifyCapability,
        );
}
```

**Comment by eernstg** [comment]
Hello, @RicoLiu, it is a compile-time error to use a class as its own superclass:

```dart
class Reflectable extends Reflectable {...} // Error!
```

You can still give a class the same name as its superclass (if you actually, really want to do that), if you're importing the superclass with a prefix:

```dart
// Library 'lib.dart'.
class C {}

// Library 'main.dart'.
import 'lib.dart' as lib;

class C extends lib.C {} // OK.
```

But it looks like the intended name might be `GfyReflectable`, in which case you might want to do this:

```dart
class GfyReflectable extends Reflectable {
  const GfyReflectable()
      : super.fromList(const [
          instanceInvokeCapability,
          libraryCapability,
          staticInvokeCapability,
          const TopLevelInvokeCapability(r'^(jsonDecode)$'),
          newInstanceCapability,
          metadataCapability,
          reflectedTypeCapability,
          declarationsCapability,
          invokingCapability,
          superclassQuantifyCapability,
        ]);
}
```

Note that you need to use the `fromList` constructor when you're passing 10 or more arguments.

The reflectable code generator is not intended to handle compile-time errors in the underlying Dart code, so it's a good idea to run the analyzer on the code in order to make sure that the code which is passed to the code generator doesn't have errors like this.

There will be some errors when you do that, because the code will refer to generated declarations. E.g., `main` will almost certainly call `initializeReflectable()`, and that's undefined until the generated file is available. However, such direct references to generated code should be really rare, so you'll basically just see the error about `initializeReflectable` and the error about importing a library that doesn't (yet) exist. When the code is in good shape, you can run the reflectable code generator.
